apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  type: NodePort  # Exposes the hub externally
  selector:
    app: selenium-hub
  ports:
    - name: hub
      protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 30044
    - name: event-bus-pub
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: event-bus-sub
      protocol: TCP
      port: 4443
      targetPort: 4443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:latest
          ports:
            - containerPort: 4444

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      initContainers:
        - name: wait-for-hub
          image: busybox
          command: ['sh', '-c', 'until nc -z selenium-hub 4444; do echo waiting for selenium hub; sleep 5; done;']
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:latest
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5900
